// Generated by CoffeeScript 1.6.3
(function() {
  var Camera,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Camera = (function(_super) {
    __extends(Camera, _super);

    function Camera(_arg) {
      var aspect, far, fov, height, near, pos, width, _ref;
      _ref = _arg != null ? _arg : {}, width = _ref.width, height = _ref.height, pos = _ref.pos;
      this.pos = pos;
      fov = 45;
      aspect = width / height;
      near = 0.1;
      far = 10000;
      THREE.PerspectiveCamera.call(this, fov, aspect, near, far);
      this.position.set(pos.x, pos.y, pos.z);
      return this;
    }

    Camera.prototype.reset = function() {
      return this.position.set(this.pos.x, this.pos.y, this.pos.z);
    };

    return Camera;

  })(THREE.PerspectiveCamera);

  window.Camera = Camera;

}).call(this);

/*
//@ sourceMappingURL=Camera.map
*/
