// Generated by CoffeeScript 1.6.3
(function() {
  var Main,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Main = (function() {
    function Main() {
      this.onWindowResize = __bind(this.onWindowResize, this);
      this.scene = new THREE.Scene();
      this.renderer = new THREE.WebGLRenderer({
        antialias: true,
        alpha: false
      });
      this.renderer.setClearColor(0x9C9C9C);
      this.camera = new Camera({
        width: window.innerWidth,
        height: window.innerHeight
      });
      window.addEventListener('resize', this.onWindowResize, false);
    }

    Main.prototype.render = function() {
      this.scene.updateMatrixWorld();
      this.renderer.clear();
      return this.renderer.render(this.scene, this.camera);
    };

    Main.prototype.animate = function() {
      requestAnimationFrame(animate);
      return render();
    };

    Main.prototype.onWindowResize = function() {
      this.camera.aspect = window.innerWidth / window.innerHeight;
      this.camera.updateProjectionMatrix();
      return this.renderer.setSize(window.innerWidth, window.innerHeight);
    };

    return Main;

  })();

  window.Main = Main;

}).call(this);

/*
//@ sourceMappingURL=Main.map
*/
