// Generated by CoffeeScript 1.6.3
(function() {
  var Player;

  Player = (function() {
    function Player(_arg) {
      var name;
      name = (_arg != null ? _arg : {}).name;
      this.name = name != null ? name : name = "Please name me";
      this.health = 100.0;
      return this;
    }

    Player.prototype.getName = function() {
      return this.name;
    };

    Player.prototype.setName = function(newName) {
      return this.name = newName;
    };

    Player.prototype.getHealth = function() {
      return this.health;
    };

    Player.prototype.setHealth = function(amount) {
      return this.health = amount;
    };

    return Player;

  })();

  window.Player = Player;

}).call(this);

/*
//@ sourceMappingURL=Player.map
*/
